### ISSUE TITLE
Is there any video or blog-post available for this tutorial ?

### ISSUE THREAD

**Issue by collegeimprovements** [jeremyevans/slab#1]

**Comment by jeremyevans** [comment]
Unfortunately, no.  I gave a 2-part presentation using this to the Sacramento Ruby Meetup in October and November, but it wasn't video taped.  I'm considering submitting it as a workshop to a ruby conference, but I don't have any concrete plans yet.

If you have any general questions about it, I'll certainly try to answer them.
